version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_new
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
